changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Misc Changes
      labels:
        - '*'
