queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Misc tests (lint)
      - status-success=Misc tests (format)
      - status-success=Unit tests (py38-flask1)
      - status-success=Unit tests (py39-flask1)
      - status-success=Unit tests (py310-flask1)
      - status-success=Unit tests (py311-flask1)
      - status-success=Unit tests (py312-flask1)
      - status-success=Unit tests (py38-flask2)
      - status-success=Unit tests (py39-flask2)
      - status-success=Unit tests (py310-flask2)
      - status-success=Unit tests (py311-flask2)
      - status-success=Unit tests (py312-flask2)

pull_request_rules:

  - name: Merge on approval
    actions:
      queue:
        name: default
        method: rebase
    conditions:
    - label!=WIP
    - approved-reviews-by=@fedora-infra/authdev
    - "#approved-reviews-by>=1"
    - status-success=DCO
    - status-success=Misc tests (lint)
    - status-success=Misc tests (format)
    - status-success=Unit tests (py38-flask1)
    - status-success=Unit tests (py39-flask1)
    - status-success=Unit tests (py310-flask1)
    - status-success=Unit tests (py311-flask1)
    - status-success=Unit tests (py312-flask1)
    - status-success=Unit tests (py38-flask2)
    - status-success=Unit tests (py39-flask2)
    - status-success=Unit tests (py310-flask2)
    - status-success=Unit tests (py311-flask2)
    - status-success=Unit tests (py312-flask2)
