on:
  push:
  pull_request:

name: Tests

jobs:
  tests-misc:
    name: Misc tests
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: krb5-devel openldap-devel
    strategy:
      matrix:
        tox_env:
          - lint
          - format
    runs-on: ubuntu-latest

  tests-unit:
    name: Unit tests
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.pyver }}-${{ matrix.flaskver }}
          dnf_install: krb5-devel openldap-devel
    strategy:
      matrix:
        pyver:
          - py38
          - py39
          - py310
          - py311
        flaskver:
          - flask1
          - flask2
          - flask3
    runs-on: ubuntu-latest

  # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    needs:
      - tests-unit
      - tests-misc
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI 🚀
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'rc')  # only publish to PyPI on final tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/flask-mod-auth-gssapi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create a GitHub Release 📢
    needs:
      - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/*
          fail_on_unmatched_files: true
          generate_release_notes: true
