on:
  push:
    branches:
      - stable
      - dev
  pull_request:
    branches:
      - stable
      - dev

name: Tests

jobs:
  misc_tests:
    name: Misc tests
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: krb5-devel openldap-devel
    strategy:
      matrix:
        tox_env:
          - lint
          - format
    runs-on: ubuntu-latest

  unit_test:
    name: Unit tests
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.pyver }}-${{ matrix.flaskver }}
          dnf_install: krb5-devel openldap-devel
    strategy:
      matrix:
        pyver:
          - py38
          - py39
          - py310
          - py311
        flaskver:
          - flask1
          - flask2
    runs-on: ubuntu-latest
